/*
* generated by Xtext
*/
package org.scribble.editor.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.scribble.editor.dsl.services.ScribbleDslGrammarAccess;

public class ScribbleDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ScribbleDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.scribble.editor.dsl.parser.antlr.internal.InternalScribbleDslParser createParser(XtextTokenStream stream) {
		return new org.scribble.editor.dsl.parser.antlr.internal.InternalScribbleDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public ScribbleDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScribbleDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
