/*
 * generated by Xtext
 */
package org.scribble.trace.editor.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.scribble.trace.editor.dsl.ui.internal.ScribbleTraceDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScribbleTraceDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScribbleTraceDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScribbleTraceDslActivator.getInstance().getInjector(ScribbleTraceDslActivator.ORG_SCRIBBLE_TRACE_EDITOR_DSL_SCRIBBLETRACEDSL);
	}
	
}
