/**
 * generated by Xtext
 */
package org.scribble.editor.dsl.validation;

import org.scribble.editor.dsl.validation.AbstractScribbleDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ScribbleDslValidator extends AbstractScribbleDslValidator {
}
