/*
 * generated by Xtext
 */
package org.scribble.trace.editor.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractScribbleTraceDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.scribble.trace.editor.dsl.scribbleTraceDsl.ScribbleTraceDslPackage.eINSTANCE);
		return result;
	}
}
