/*
 * generated by Xtext
 */
package org.scribble.trace.editor.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScribbleTraceDslUiModule extends org.scribble.trace.editor.dsl.ui.AbstractScribbleTraceDslUiModule {
	public ScribbleTraceDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
