/*
 * generated by Xtext
 */
package org.scribble.editor.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScribbleDslRuntimeModule extends org.scribble.editor.dsl.AbstractScribbleDslRuntimeModule {

}
