/**
 * generated by Xtext
 */
package org.scribble.trace.editor.dsl.ui.contentassist;

import org.scribble.trace.editor.dsl.ui.contentassist.AbstractScribbleTraceDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ScribbleTraceDslProposalProvider extends AbstractScribbleTraceDslProposalProvider {
}
