/**
 * generated by Xtext
 */
package org.scribble.trace.editor.dsl.validation;

import org.scribble.trace.editor.dsl.validation.AbstractScribbleTraceDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ScribbleTraceDslValidator extends AbstractScribbleTraceDslValidator {
}
