//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-04/09/2009 09:05 AM(mockbuild)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.07 at 02:37:02 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.scribble.org/monitor", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.scribble.protocol.monitor.model;
