//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 09:08:32 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.scribble.org/monitor", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.scribble.protocol.monitor.model;
