/*
* generated by Xtext
*/
package org.scribble.trace.editor.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ScribbleTraceDslStandaloneSetup extends ScribbleTraceDslStandaloneSetupGenerated{

	public static void doSetup() {
		new ScribbleTraceDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

