/*
 * generated by Xtext
 */
package org.scribble.trace.editor.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScribbleTraceDslRuntimeModule extends org.scribble.trace.editor.dsl.AbstractScribbleTraceDslRuntimeModule {

}
