/*
* generated by Xtext
*/
package org.scribble.trace.editor.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ScribbleTraceDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.scribble.trace.editor.dsl.ui.internal.ScribbleTraceDslActivator.getInstance().getInjector("org.scribble.trace.editor.dsl.ScribbleTraceDsl");
	}
	
}
