/*
 * generated by Xtext
 */
package org.scribble.editor.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.scribble.editor.dsl.ui.internal.ScribbleDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScribbleDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScribbleDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScribbleDslActivator.getInstance().getInjector(ScribbleDslActivator.ORG_SCRIBBLE_EDITOR_DSL_SCRIBBLEDSL);
	}
	
}
