/*
 * generated by Xtext
 */
package org.scribble.editor.dsl.ui.contentassist

import org.scribble.editor.dsl.ui.contentassist.AbstractScribbleDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ScribbleDslProposalProvider extends AbstractScribbleDslProposalProvider {
}
